<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Auth Key' => '',
    'Content' => 'Nội dung',
    'Create' => 'Thêm mới',
    'Create Customer' => '',
    'Create Customer Resource' => '',
    'Create Note' => '',
    'Create Partner' => '',
    'Create Project' => '',
    'Create User' => '',
    'Created At' => '',
    'Created By' => '',
    'Customer ID' => '',
    'Customer Resource ID' => '',
    'Customer Resources' => '',
    'Customers' => '',
    'Cập nhật' => '',
    'Delete' => '',
    'Delivery Date' => '',
    'Dự án' => '',
    'Email' => '',
    'End Date' => '',
    'Full Name' => '',
    'ID' => '',
    'Name' => '',
    'Notes' => '',
    'Partner ID' => '',
    'Partners' => '',
    'Password Hash' => '',
    'Password Reset Token' => '',
    'Phone Number' => '',
    'Project ID' => '',
    'Projects' => '',
    'Reset' => '',
    'Role' => '',
    'Search' => '',
    'Start Date' => '',
    'Status' => '',
    'Thêm mới dự án' => '',
    'Title' => 'Tiêu đề',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Updated At' => '',
    'Updated By' => '',
    'User ID' => '',
    'Username' => '',
    'Users' => '',
    'Create Project' => 'Thêm mới dự án',
];
