<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Auth Key' => '',
    'Content' => 'Mô tả',
    'Create' => 'Thêm mới',
    'Create Customer' => 'Thêm mới khách hàng',
    'Create Note' => '',
    'Create Partner' => 'Thêm mới đối tác',
    'Create User' => 'Thêm mới nhân viên',
    'Created At' => '',
    'Created By' => '',
    'Customer ID' => '',
    'Customer Resource ID' => 'Nguồn khách hàng',
    'Customer Resources' => 'Nguồn khách hàng',
    'Customers' => '',
    'Cập nhật' => '',
    'Delete' => '',
    'Delivery Date' => 'Ngày giao khách',
    'Dự án' => '',
    'Email' => '',
    'End Date' => 'Ngày kết thúc',
    'Full Name' => 'Họ tên',
    'ID' => '',
    'Name' => 'Tên',
    'Notes' => 'Ghi chú',
    'Partner ID' => 'Đối tác',
    'Partners' => 'Đối tác',
    'Password Hash' => '',
    'Password Reset Token' => '',
    'Phone Number' => 'Số điện thoại',
    'Project ID' => 'Dự án',
    'Projects' => 'Dự án',
    'Reset' => '',
    'Role' => '',
    'Search' => '',
    'Start Date' => 'Ngày bắt đầu',
    'Status' => 'Trạng thái',
    'Thêm mới dự án' => '',
    'Title' => 'Tiêu đề',
    'Update' => 'Cập nhật',
    'Update {modelClass}: ' => '',
    'Updated At' => '',
    'Updated By' => '',
    'User ID' => '',
    'Username' => 'Tài khoản',
    'Users' => 'Danh sách nhân viên',
    'Create Project' => 'Thêm mới dự án',
    'Create Customer Resource' => 'Nguồn khách hàng',
    'Customer Resource Name' => 'Nguồn khách hàng'
];
